let load_audio_file = failwith "unimplemented"
let play_audio = failwith "unimplemented"
let pause_audio = failwith "unimplemented"
let resume_audio = failwith "unimplemented"
let skip_forward = failwith "unimplemented"
let skip_backward = failwith "unimplemented"
let adjust_volume = failwith "unimplemented"
let mute_audio = failwith "unimplemented"
